spring:
  application.name: ecommerce-hub

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ecommerce_hub}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:ecommerce_hub}
    password: ${DATABASE_PASSWORD:password}

  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
    defer-datasource-initialization: true

  sql.init:
    mode: always
    data-locations: classpath:data.sql

  jackson.property-naming-strategy: SNAKE_CASE